{ pkgs, ... }:

{
  home.packages = with pkgs; [
    cachix
  ];
  home.file.".config/nix/nix.conf".text = ''
    # Auto-generated by flexnix
    
    # Enable flakes and nix-command
    experimental-features = nix-command flakes
    
    # Add official Nix cache and flexnix cache
    substituters = https://cache.nixos.org https://flexnix.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= flexnix.cachix.org-1:GtP6/JskZE8G98ScdGcttekZO/588IoGUZBA3zKsoeQ=
  '';
}
