/*
 * File: home/modules/services/secrets.nix
 * (Updated with ssh config)
 */
{ pkgs, config, inputs, ... }:

{
  # 1. Impor modul 'agenix'
  imports = [
    inputs.agenix.homeManagerModules.default
  ];
  
  # 2. Instal 'age' CLI
  home.packages = [
    pkgs.age
  ];

  # 3. Tentukan lokasi kunci privat
  age.identityPaths = [
    "/etc/nix/age.key"
  ];

  # 4. Definisikan secrets Anda (TETAP SAMA)
  age.secrets = {
    "ssh-nixvali" = {
      file = ../../../secrets/ssh-nixvali.age;
      path = "${config.home.homeDirectory}/.ssh/id_ed25519_nixvali";
      mode = "0600";
    };
    "ssh-liyankova" = {
      file = ../../../secrets/ssh-liyankova.age;
      path = "${config.home.homeDirectory}/.ssh/id_ed25519_liyankova";
      mode = "0600";
    };
    "ssh-valistudio" = {
      file = ../../../secrets/ssh-valistudio.age;
      path = "${config.home.homeDirectory}/.ssh/id_ed25519_valistudio";
      mode = "0600";
    };
  };

  # 5. --- TAMBAHKAN BLOK BARU INI ---
  # Define the SSH config file declaratively
  home.file.".ssh/config" = {
    # This creates ~/.ssh/config
    text = ''
      # Auto-generated by flexnix
      
      # Automatically add keys to ssh-agent
      AddKeysToAgent yes
      # UseKeychain yes # macOS specific, but harmless on Linux
      
      # --- GitHub Account Aliases ---

      # Nixval Account (Primary)
      Host github.com-nixvali
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_ed25519_nixvali
        IdentitiesOnly yes

      # Liyankova Account
      Host github.com-liyankova
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_ed25519_liyankova
        IdentitiesOnly yes

      # Valistudio Account
      Host github.com-valistudio
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_ed25519_valistudio
        IdentitiesOnly yes
    '';
    # Set permissions for the config file
    # mode = "0600";
  };
}
