
/*
 * File: home/modules/desktop/hyprland/hyprland.nix
 *
 * Description:
 * Manages Home Manager dotfiles and user packages for Hyprland.
 * This is loaded in *both* NixOS and non-NixOS modes.
 */
{ pkgs, ... }:

{
  # 1. Install user-level packages (the DE "support system")
  #
  # NOTE for non-NixOS users:
  # This does NOT install 'hyprland' itself.
  # You must install 'hyprland' via your host system's package
  # manager (e.g., 'apt install hyprland').
  #
  # On NixOS, 'hyprland' is installed by the system module.
  home.packages = with pkgs; [
    # Bar and Launchers
    waybar
    wofi
    
    # Notification daemon
    mako
    
    # Screenshot tool
    grim
    slurp
    
    # Screen locking
    swaylock-effects # Or just 'swaylock'
    
    # Wallpaper daemon
    swww # Or 'hyprpaper'
    
    # Utility
    wl-clipboard # Wayland clipboard tools
    hyprland-protocols
    
    # (Other tools: foot, wezterm, etc.)
  ];

  # 2. Declaratively manage dotfiles
  # We use 'home.file."path".text' for simple stubs,
  # but 'home.file."path".source' is better for large configs.
  
  # Stub for Hyprland config
  home.file.".config/hypr/hyprland.conf".text = ''
    # Auto-generated by flexnix
    # Source this file from your main config
    
    # Example: Basic monitor setup
    monitor=,preferred,auto,1
    
    # Example: Autostart support programs
    exec-once = waybar
    exec-once = mako
    exec-once = swww-init
  '';

  # Stub for Waybar
  home.file.".config/waybar/config".text = ''
    {
      "layer": "top",
      "modules-left": ["clock"],
      "modules-right": ["cpu", "memory"]
    }
  '';
  
  home.file.".config/waybar/style.css".text = ''
    /* Add some basic styling */
    * { font-family: "JetBrainsMono Nerd Font"; }
  '';
  
  # Stub for Mako
  home.file.".config/mako/config".text = ''
    [default]
    border-size=2
    padding=4
  '';
  
  # (Add stubs for wofi, swaylock, etc. here)
}
